### ISSUE TITLE
the paper about this code

### ISSUE THREAD

**Issue by TimZhang001** [smiler96/PFM-and-PEFM-for-Image-Anomaly-Detection-and-Segmentation#1]
The idea of ​​this article is very interesting, and I had similar ideas before, but I didn't get good results. I would love to see your paper, can you share a link to your paper?

**Comment by smiler96** [comment]
> The idea of ​​this article is very interesting, and I had similar ideas before, but I didn't get good results. I would love to see your paper, can you share a link to your paper?

Thanks for your attention. The paper of PFM can refer to this [https://ieeexplore.ieee.org/document/9795121](https://ieeexplore.ieee.org/document/9795121), and the PEFM has not been published, and you can refer to [researchgate](https://www.researchgate.net/publication/361254312_Position_Encoding_Enhanced_Feature_Mapping_for_Image_Anomaly_Detection)
Hope this can help you a lot!
