### ISSUE TITLE
Thanks for your exciting efforts! I would like to known how to download the pdf. 

### ISSUE THREAD

**Issue by BadSeedX** [smiler96/PFM-and-PEFM-for-Image-Anomaly-Detection-and-Segmentation#2]

**Comment by smiler96** [comment]
> _No description provided._

Thanks for your attention. The paper of PFM can refer to this https://ieeexplore.ieee.org/document/9795121, and the PEFM has not been published, and you can refer to [researchgate](https://www.researchgate.net/publication/361254312_Position_Encoding_Enhanced_Feature_Mapping_for_Image_Anomaly_Detection)
Hope this can help you a lot!

**Comment by BadSeedX** [comment]
> > _No description provided._
> 
> Thanks for your attention. The paper of PFM can refer to this https://ieeexplore.ieee.org/document/9795121, and the PEFM has not been published, and you can refer to [researchgate](https://www.researchgate.net/publication/361254312_Position_Encoding_Enhanced_Feature_Mapping_for_Image_Anomaly_Detection) Hope this can help you a lot!

Thank you for your reply！I sent you a request on researchgate, looking forward to the paper being published.
