### ISSUE TITLE
只有正样本没有负样本,是否能用

### ISSUE THREAD

**Issue by monkeycc** [smiler96/PFM-and-PEFM-for-Image-Anomaly-Detection-and-Segmentation#3]
只有正样本没有负样本,是否能用

比如 把 正样本 作为 预训练特征映射
然后对比?

**Comment by smiler96** [comment]
> 只有正样本没有负样本,是否能用
> 
> 比如 把 正样本 作为 预训练特征映射 然后对比?

PFM是仅利用正常样本训练的，没有用异常样本。

**Comment by XHD5656123** [comment]
DFC那篇有用到异常样本的半监督文章的代码能否开源，供学习参考呀？
