### ISSUE TITLE
 No such file or directory: './result/MB-PFM_resnet34-resnet50_888/ckpt/bottle_2.pth'

### ISSUE THREAD

**Issue by monkeycc** [smiler96/PFM-and-PEFM-for-Image-Anomaly-Detection-and-Segmentation#4]
python MB-PFM-ResNet.py --train --gpu_id 0 --batch_size 8 --epochs 200 --resize 256 --data_trans imagenet --loss_type l2norm+l2 --data_root F:/mvtec_anomaly_detection

```
2022-11-25 11:19:49.599 | INFO     | __main__:<module>:478 - Namespace(agent_S='resnet34', agent_T='resnet50', batch_size=8, data_root='F:/mvtec_anomaly_detection', data_trans='imagenet', epochs=200, gpu_id='0', latent_dim=200, loss_type='l2norm+l2', lr2=0.003, lr3=0.0003, lr4=0.0003, post_smooth=0, resize=256, seed=888, train=False, weight_decay=1e-05)
D:\anaconda\envs\pca_kmeans_change_detection\lib\site-packages\torchvision\transforms\transforms.py:288: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
Downloading: "https://download.pytorch.org/models/resnet34-b627a593.pth" to C:\Users\ai/.cache\torch\hub\checkpoints\resnet34-b627a593.pth
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 83.3M/83.3M [00:02<00:00, 37.0MB/s]
Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to C:\Users\ai/.cache\torch\hub\checkpoints\resnet50-0676ba61.pth
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 97.8M/97.8M [00:01<00:00, 64.6MB/s]
Traceback (most recent call last):
  File "MB-PFM-ResNet.py", line 524, in <module>
    metrix = model.test(cal_pro=True)
  File "MB-PFM-ResNet.py", line 294, in test
    self.load_project_model()
  File "MB-PFM-ResNet.py", line 416, in load_project_model
    self.projector2.load_state_dict(torch.load(self.ckpt2))
  File "D:\anaconda\envs\pca_kmeans_change_detection\lib\site-packages\torch\serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\anaconda\envs\pca_kmeans_change_detection\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\anaconda\envs\pca_kmeans_change_detection\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './result/MB-PFM_resnet34-resnet50_888/ckpt/bottle_2.pth'
```

**Comment by smiler96** [comment]
> python MB-PFM-ResNet.py --train --gpu_id 0 --batch_size 8 --epochs 200 --resize 256 --data_trans imagenet --loss_type l2norm+l2 --data_root F:/mvtec_anomaly_detection
> 
> ```
> 2022-11-25 11:19:49.599 | INFO     | __main__:<module>:478 - Namespace(agent_S='resnet34', agent_T='resnet50', batch_size=8, data_root='F:/mvtec_anomaly_detection', data_trans='imagenet', epochs=200, gpu_id='0', latent_dim=200, loss_type='l2norm+l2', lr2=0.003, lr3=0.0003, lr4=0.0003, post_smooth=0, resize=256, seed=888, train=False, weight_decay=1e-05)
> D:\anaconda\envs\pca_kmeans_change_detection\lib\site-packages\torchvision\transforms\transforms.py:288: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
>   "Argument interpolation should be of type InterpolationMode instead of int. "
> Downloading: "https://download.pytorch.org/models/resnet34-b627a593.pth" to C:\Users\ai/.cache\torch\hub\checkpoints\resnet34-b627a593.pth
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 83.3M/83.3M [00:02<00:00, 37.0MB/s]
> Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to C:\Users\ai/.cache\torch\hub\checkpoints\resnet50-0676ba61.pth
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 97.8M/97.8M [00:01<00:00, 64.6MB/s]
> Traceback (most recent call last):
>   File "MB-PFM-ResNet.py", line 524, in <module>
>     metrix = model.test(cal_pro=True)
>   File "MB-PFM-ResNet.py", line 294, in test
>     self.load_project_model()
>   File "MB-PFM-ResNet.py", line 416, in load_project_model
>     self.projector2.load_state_dict(torch.load(self.ckpt2))
>   File "D:\anaconda\envs\pca_kmeans_change_detection\lib\site-packages\torch\serialization.py", line 594, in load
>     with _open_file_like(f, 'rb') as opened_file:
>   File "D:\anaconda\envs\pca_kmeans_change_detection\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
>     return _open_file(name_or_buffer, mode)
>   File "D:\anaconda\envs\pca_kmeans_change_detection\lib\site-packages\torch\serialization.py", line 211, in __init__
>     super(_open_file, self).__init__(open(name, mode))
> FileNotFoundError: [Errno 2] No such file or directory: './result/MB-PFM_resnet34-resnet50_888/ckpt/bottle_2.pth'
> ```

line 442，change store_false to store_true

**Comment by monkeycc** [comment]
```
 MB-PFM-ResNet.py
parser.add_argument("--train", action="store_false")
```


python MB-PFM-ResNet.py --train --gpu_id 0 --batch_size 8 --epochs 200 --resize 256 --data_trans imagenet --loss_type l2norm+l2 --data_root F:/mvtec_anomaly_detection
```

2022-11-25 12:58:01.427 | INFO     | __main__:<module>:478 - Namespace(agent_S='resnet34', agent_T='resnet50', batch_size=8, data_root='F:/mvtec_anomaly_detection', data_trans='imagenet', epochs=200, gpu_id='0', latent_dim=200, loss_type='l2norm+l2', lr2=0.003, lr3=0.0003, lr4=0.0003, post_smooth=0, resize=256, seed=888, train=True, weight_decay=1e-05)
MB-PFM-ResNet.py:493: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  trans_x = T.Compose([T.Resize(args.resize, Image.ANTIALIAS),
D:\anaconda\envs\AI\lib\site-packages\torchvision\transforms\transforms.py:329: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  warnings.warn(
D:\anaconda\envs\AI\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
D:\anaconda\envs\AI\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet34_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet34_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
D:\anaconda\envs\AI\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
  File "MB-PFM-ResNet.py", line 521, in <module>
    model.train(epochs=args.epochs)
  File "MB-PFM-ResNet.py", line 190, in train
    for i, (x, _, _, _) in enumerate(self.trainloader):
  File "D:\anaconda\envs\AI\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "D:\anaconda\envs\AI\lib\site-packages\torch\utils\data\dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "D:\anaconda\envs\AI\lib\site-packages\torch\utils\data\dataloader.py", line 1359, in _process_data
    data.reraise()
  File "D:\anaconda\envs\AI\lib\site-packages\torch\_utils.py", line 543, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\anaconda\envs\AI\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\anaconda\envs\AI\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda\envs\AI\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\0SDXX\PFM-and-PEFM-for-Image-Anomaly-Detection-and-Segmentation-main\dataset\mvtec.py", line 71, in __getitem__
    name = names[-2] + "_" + names[-1]
IndexError: list index out of range

```

**Comment by smiler96** [comment]
> ```
>  MB-PFM-ResNet.py
> parser.add_argument("--train", action="store_false")
> ```
> 
> 
>     
>  
>   
> 
> python MB-PFM-ResNet.py --train --gpu_id 0 --batch_size 8 --epochs 200 --resize 256 --data_trans imagenet --loss_type l2norm+l2 --data_root F:/mvtec_anomaly_detection
> 
> 
> ```
> 
> 2022-11-25 12:58:01.427 | INFO     | __main__:<module>:478 - Namespace(agent_S='resnet34', agent_T='resnet50', batch_size=8, data_root='F:/mvtec_anomaly_detection', data_trans='imagenet', epochs=200, gpu_id='0', latent_dim=200, loss_type='l2norm+l2', lr2=0.003, lr3=0.0003, lr4=0.0003, post_smooth=0, resize=256, seed=888, train=True, weight_decay=1e-05)
> MB-PFM-ResNet.py:493: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
>   trans_x = T.Compose([T.Resize(args.resize, Image.ANTIALIAS),
> D:\anaconda\envs\AI\lib\site-packages\torchvision\transforms\transforms.py:329: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
>   warnings.warn(
> D:\anaconda\envs\AI\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
>   warnings.warn(
> D:\anaconda\envs\AI\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet34_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet34_Weights.DEFAULT` to get the most up-to-date weights.
>   warnings.warn(msg)
> D:\anaconda\envs\AI\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
>   warnings.warn(msg)
> Traceback (most recent call last):
>   File "MB-PFM-ResNet.py", line 521, in <module>
>     model.train(epochs=args.epochs)
>   File "MB-PFM-ResNet.py", line 190, in train
>     for i, (x, _, _, _) in enumerate(self.trainloader):
>   File "D:\anaconda\envs\AI\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
>     data = self._next_data()
>   File "D:\anaconda\envs\AI\lib\site-packages\torch\utils\data\dataloader.py", line 1333, in _next_data
>     return self._process_data(data)
>   File "D:\anaconda\envs\AI\lib\site-packages\torch\utils\data\dataloader.py", line 1359, in _process_data
>     data.reraise()
>   File "D:\anaconda\envs\AI\lib\site-packages\torch\_utils.py", line 543, in reraise
>     raise exception
> IndexError: Caught IndexError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "D:\anaconda\envs\AI\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
>     data = fetcher.fetch(index)
>   File "D:\anaconda\envs\AI\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "D:\anaconda\envs\AI\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "D:\0SDXX\PFM-and-PEFM-for-Image-Anomaly-Detection-and-Segmentation-main\dataset\mvtec.py", line 71, in __getitem__
>     name = names[-2] + "_" + names[-1]
> IndexError: list index out of range
> ```

你这个是数据路径有问题，调试一下吧
