### ISSUE TITLE
No such file or directory: './result/MB-PFM_resnet34-resnet50_888/ckpt/bottle_2.pth'

### ISSUE THREAD

**Issue by monkeycc** [smiler96/PFM-and-PEFM-for-Image-Anomaly-Detection-and-Segmentation#5]
```
raceback (most recent call last):
  File "MB-PFM-ResNet.py", line 524, in <module>
    metrix = model.test(cal_pro=True)
  File "MB-PFM-ResNet.py", line 294, in test
    self.load_project_model()
  File "MB-PFM-ResNet.py", line 416, in load_project_model
    self.projector2.load_state_dict(torch.load(self.ckpt2))
  File "/home/Intsoft/anaconda3/envs/PFM/lib/python3.7/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/Intsoft/anaconda3/envs/PFM/lib/python3.7/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/Intsoft/anaconda3/envs/PFM/lib/python3.7/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './result/MB-PFM_resnet34-resnet50_888/ckpt/bottle_2.pth'

```

**Comment by smiler96** [comment]
> ```
> raceback (most recent call last):
>   File "MB-PFM-ResNet.py", line 524, in <module>
>     metrix = model.test(cal_pro=True)
>   File "MB-PFM-ResNet.py", line 294, in test
>     self.load_project_model()
>   File "MB-PFM-ResNet.py", line 416, in load_project_model
>     self.projector2.load_state_dict(torch.load(self.ckpt2))
>   File "/home/Intsoft/anaconda3/envs/PFM/lib/python3.7/site-packages/torch/serialization.py", line 771, in load
>     with _open_file_like(f, 'rb') as opened_file:
>   File "/home/Intsoft/anaconda3/envs/PFM/lib/python3.7/site-packages/torch/serialization.py", line 270, in _open_file_like
>     return _open_file(name_or_buffer, mode)
>   File "/home/Intsoft/anaconda3/envs/PFM/lib/python3.7/site-packages/torch/serialization.py", line 251, in __init__
>     super(_open_file, self).__init__(open(name, mode))
> FileNotFoundError: [Errno 2] No such file or directory: './result/MB-PFM_resnet34-resnet50_888/ckpt/bottle_2.pth'
> ```

Oh, you should make a training procedure first and there will be './result/MB-PFM_resnet34-resnet50_888/ckpt/bottle_2.pth' for testing. It can help.

**Comment by smiler96** [comment]
> ```
> raceback (most recent call last):
>   File "MB-PFM-ResNet.py", line 524, in <module>
>     metrix = model.test(cal_pro=True)
>   File "MB-PFM-ResNet.py", line 294, in test
>     self.load_project_model()
>   File "MB-PFM-ResNet.py", line 416, in load_project_model
>     self.projector2.load_state_dict(torch.load(self.ckpt2))
>   File "/home/Intsoft/anaconda3/envs/PFM/lib/python3.7/site-packages/torch/serialization.py", line 771, in load
>     with _open_file_like(f, 'rb') as opened_file:
>   File "/home/Intsoft/anaconda3/envs/PFM/lib/python3.7/site-packages/torch/serialization.py", line 270, in _open_file_like
>     return _open_file(name_or_buffer, mode)
>   File "/home/Intsoft/anaconda3/envs/PFM/lib/python3.7/site-packages/torch/serialization.py", line 251, in __init__
>     super(_open_file, self).__init__(open(name, mode))
> FileNotFoundError: [Errno 2] No such file or directory: './result/MB-PFM_resnet34-resnet50_888/ckpt/bottle_2.pth'
> ```

have you successfully made a training? if not, please make it.

**Comment by smiler96** [comment]
> ```
> raceback (most recent call last):
>   File "MB-PFM-ResNet.py", line 524, in <module>
>     metrix = model.test(cal_pro=True)
>   File "MB-PFM-ResNet.py", line 294, in test
>     self.load_project_model()
>   File "MB-PFM-ResNet.py", line 416, in load_project_model
>     self.projector2.load_state_dict(torch.load(self.ckpt2))
>   File "/home/Intsoft/anaconda3/envs/PFM/lib/python3.7/site-packages/torch/serialization.py", line 771, in load
>     with _open_file_like(f, 'rb') as opened_file:
>   File "/home/Intsoft/anaconda3/envs/PFM/lib/python3.7/site-packages/torch/serialization.py", line 270, in _open_file_like
>     return _open_file(name_or_buffer, mode)
>   File "/home/Intsoft/anaconda3/envs/PFM/lib/python3.7/site-packages/torch/serialization.py", line 251, in __init__
>     super(_open_file, self).__init__(open(name, mode))
> FileNotFoundError: [Errno 2] No such file or directory: './result/MB-PFM_resnet34-resnet50_888/ckpt/bottle_2.pth'
> ```

I upload the weight of models with Baidu Yun.
The link is [https://pan.baidu.com/s/1A11N6pp21aDDPQxNoAUwcg?pwd=obui ](https://pan.baidu.com/s/1A11N6pp21aDDPQxNoAUwcg?pwd=obui)(password: obui)
Any question you can email to me by [wanqian_hust@163.com](mailto:wanqian_hust@163.com).
