### ISSUE TITLE
No such file or directory: './result/MB-PFM_resnet34-resnet50_888/ckpt/bottle_2.pth'

### ISSUE THREAD

**Issue by shuaiqidexiaojiejie** [smiler96/PFM-and-PEFM-for-Image-Anomaly-Detection-and-Segmentation#6]
It's nice to read your program on Github. I met a problem when running the project you provided. I hope to get your help.
![2023-05-24 12-54-03屏幕截图](https://github.com/smiler96/PFM-and-PEFM-for-Image-Anomaly-Detection-and-Segmentation/assets/101921170/b8052c1a-bcb0-4a37-bce8-a42d1384c22f)

**Comment by smiler96** [comment]
> It's nice to read your program on Github. I met a problem when running the project you provided. I hope to get your help. ![2023-05-24 12-54-03屏幕截图](https://user-images.githubusercontent.com/101921170/240491737-b8052c1a-bcb0-4a37-bce8-a42d1384c22f.png)

The weight is large and i upload it with Baidu Netdisk.
The links is [https://pan.baidu.com/s/1yt_0cAQ88WAIX3XghMmP1g?pwd=eqyv](https://pan.baidu.com/s/1yt_0cAQ88WAIX3XghMmP1g?pwd=eqyv)  (password：eqyv)

**Comment by smiler96** [comment]
> It's nice to read your program on Github. I met a problem when running the project you provided. I hope to get your help. ![2023-05-24 12-54-03屏幕截图](https://user-images.githubusercontent.com/101921170/240491737-b8052c1a-bcb0-4a37-bce8-a42d1384c22f.png)

I upload the weight of models with Baidu Yun.
The link is [https://pan.baidu.com/s/1A11N6pp21aDDPQxNoAUwcg?pwd=obui ](https://pan.baidu.com/s/1A11N6pp21aDDPQxNoAUwcg?pwd=obui ) (password: obui)
Any question you can email to me by wanqian_hust@163.com.
